// Shareable "companion card": a square image of a companion (cosmic orb + their
// constellation sigil) with a memorable line and attribution baked in
// (ToS §7.3). Pure canvas — no network, no image-AI. Returns a PNG Blob;
// shareOrDownloadCard hands it to the native share sheet or a download.

function hashStr(str) {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619); }
  return h >>> 0;
}
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const clamp = (n) => Math.max(0, Math.min(255, n));
function hexToRgb(h) {
  h = (h || '#7c5bf5').replace('#', '');
  if (h.length === 3) h = h.split('').map((c) => c + c).join('');
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}
const toHex = (r, g, b) => '#' + [r, g, b].map((x) => clamp(Math.round(x)).toString(16).padStart(2, '0')).join('');
const lighten = (hex, a = 0.5) => { const [r, g, b] = hexToRgb(hex); return toHex(r + (255 - r) * a, g + (255 - g) * a, b + (255 - b) * a); };
const darken = (hex, a = 0.55) => { const [r, g, b] = hexToRgb(hex); return toHex(r * (1 - a), g * (1 - a), b * (1 - a)); };

function wrapLines(ctx, text, maxWidth) {
  const words = (text || '').split(/\s+/);
  const lines = [];
  let line = '';
  for (const w of words) {
    const test = line ? line + ' ' + w : w;
    if (ctx.measureText(test).width > maxWidth && line) { lines.push(line); line = w; }
    else line = test;
  }
  if (line) lines.push(line);
  return lines;
}

export function makeCardBlob({ comp, quote, profileName } = {}) {
  const W = 1080, H = 1080;
  const color = comp?.color?.primary || '#7c5bf5';
  const canvas = document.createElement('canvas');
  canvas.width = W; canvas.height = H;
  const ctx = canvas.getContext('2d');

  // Background
  ctx.fillStyle = '#06060c';
  ctx.fillRect(0, 0, W, H);
  // Color glow behind the orb
  const glow = ctx.createRadialGradient(W / 2, 360, 40, W / 2, 360, 520);
  glow.addColorStop(0, `${color}55`);
  glow.addColorStop(1, 'transparent');
  ctx.fillStyle = glow; ctx.fillRect(0, 0, W, H);

  // Orb
  const cx = W / 2, cy = 360, R = 180;
  const og = ctx.createRadialGradient(cx - 60, cy - 70, 20, cx, cy, R);
  og.addColorStop(0, lighten(color, 0.6));
  og.addColorStop(0.55, color);
  og.addColorStop(1, darken(color));
  ctx.beginPath(); ctx.arc(cx, cy, R, 0, Math.PI * 2); ctx.fillStyle = og; ctx.fill();

  // Constellation sigil (seeded by identity, like the in-app avatar)
  const rnd = mulberry32(hashStr(comp?.id || comp?.name || 'x'));
  const n = 4 + Math.floor(rnd() * 4);
  ctx.fillStyle = 'rgba(255,255,255,0.85)';
  for (let i = 0; i < n; i++) {
    const ang = rnd() * Math.PI * 2, rad = rnd() * R * 0.6;
    const x = cx + Math.cos(ang) * rad, y = cy + Math.sin(ang) * rad, r = 2 + rnd() * 5;
    ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2); ctx.fill();
  }

  // Name
  ctx.textAlign = 'center';
  ctx.fillStyle = '#f4f2ff';
  ctx.font = '700 64px Georgia, "Times New Roman", serif';
  ctx.fillText(comp?.name || 'Companion', cx, cy + R + 110);

  // Quote
  ctx.fillStyle = '#cfc9e8';
  ctx.font = '400 44px Georgia, serif';
  const q = `“${(quote || '').replace(/\s+/g, ' ').trim().slice(0, 220)}”`;
  const lines = wrapLines(ctx, q, W - 200).slice(0, 6);
  let y = 720;
  for (const ln of lines) { ctx.fillText(ln, cx, y); y += 60; }

  // Attribution
  ctx.fillStyle = `${color}`;
  ctx.font = '600 30px Georgia, serif';
  ctx.fillText('✦ Other', cx, H - 96);
  ctx.fillStyle = '#6b6880';
  ctx.font = '400 24px Arial, sans-serif';
  ctx.fillText('Generated by Other — AI companion app by Extratac LLC', cx, H - 56);

  return new Promise((resolve) => canvas.toBlob((b) => resolve(b), 'image/png'));
}

export async function shareOrDownloadCard(blob, comp) {
  if (!blob) return;
  const file = new File([blob], `other-${(comp?.name || 'companion').toLowerCase()}.png`, { type: 'image/png' });
  try {
    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      await navigator.share({ files: [file], title: 'Other', text: `${comp?.name || 'My companion'} on Other ✦` });
      return;
    }
  } catch (e) { /* fall through to download */ }
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = file.name;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
