import React, { useState } from 'react';
import { C } from '../theme.js';
import { Shell } from '../components/ui.jsx';
import SquishyBlob from '../components/SquishyBlob.jsx';
import { closenessStage, knownDuration } from '../lib/innerlife.js';

// "Your recap" — a warm, companion-narrated look back at the relationship,
// distilled from data the app already keeps: how long you've known each other,
// how close you've grown, shared history (lore), inside jokes, and letters. A
// keepsake you can copy/share (attribution baked in per ToS §7.3).
export default function Recap({ comps = [], lore = [], jokes = [], profile, onBack }) {
  const [copied, setCopied] = useState(false);
  const living = (comps || []).filter((c) => c.status !== 'deleted');
  const name = profile?.name || 'you';
  const names = living.map((c) => c.name);
  const namesText = names.length <= 1 ? (names[0] || 'your companion')
    : names.slice(0, -1).join(', ') + ' and ' + names[names.length - 1];
  // Longest-known companion sets the overall span.
  const span = living.map((c) => knownDuration(c)).filter(Boolean).sort((a, b) => b.length - a.length)[0] || 'a little while';
  const letters = living.filter((c) => c.letters?.length).flatMap((c) => c.letters.map((l) => ({ ...l, from: c.name, color: c.color?.primary || C.glow1 }))).sort((a, b) => (b.ts || 0) - (a.ts || 0));

  const intro = living.length
    ? `Over ${span}, you and ${namesText} have been building something real — here's a look back.`
    : `Your recap will fill in as you spend time together.`;

  const fmt = (t) => { try { return new Date(t).toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' }); } catch (e) { return ''; } };
  const label = { fontSize: 10, color: C.textDim, letterSpacing: 2, textTransform: 'uppercase', margin: '22px 0 10px' };

  function share() {
    const lines = [];
    lines.push(`Our recap — ${name} & ${namesText}`);
    lines.push(intro);
    living.forEach((c) => lines.push(`• ${c.name}: ${closenessStage(c).label}`));
    if (lore.length) { lines.push('Moments:'); lore.slice(0, 5).forEach((l) => lines.push(`  – remember when ${l.text}`)); }
    if (jokes.length) lines.push('Inside jokes: ' + jokes.map((j) => j.text).join(', '));
    lines.push('— Generated by Other, an AI companion app by Extratac LLC');
    const text = lines.join('\n');
    try { navigator.clipboard?.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch (e) { /* no-op */ }
  }

  return (
    <Shell>
      <div style={{ padding: '14px 16px', display: 'flex', alignItems: 'center', gap: 10, borderBottom: `1px solid ${C.border}` }}>
        <button aria-label="Back" onClick={onBack} style={{ background: 'none', border: 'none', color: C.textSoft, fontSize: 20, cursor: 'pointer' }}>←</button>
        <span style={{ fontSize: 15, fontWeight: 600 }}>Your recap</span>
        <span style={{ flex: 1 }} />
        {living.length > 0 && <button onClick={share} style={{ background: `${C.glow1}1f`, border: `1px solid ${C.glow1}66`, color: C.glow1, borderRadius: 20, padding: '5px 12px', fontSize: 12, fontWeight: 600, cursor: 'pointer', fontFamily: "'DM Sans',sans-serif" }}>{copied ? 'Copied ✓' : 'Share'}</button>}
      </div>

      <div style={{ flex: 1, minHeight: 0, overflowY: 'auto', padding: '20px 18px 48px' }}>
        <div style={{ display: 'flex', justifyContent: 'center', gap: 10, marginBottom: 16 }}>
          {living.slice(0, 3).map((c) => <SquishyBlob key={c.id} comp={c} size={64} glow vitality={1} />)}
        </div>
        <p style={{ fontFamily: "'Cormorant Garamond',serif", fontSize: 21, lineHeight: 1.5, textAlign: 'center', color: C.text, margin: '0 0 8px' }}>{intro}</p>

        {living.length > 0 && (
          <>
            <div style={label}>✦ How close you've grown</div>
            {living.map((c) => (
              <div key={c.id} style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 9 }}>
                <div style={{ width: 10, height: 10, borderRadius: '50%', background: c.color?.primary || C.glow1, flexShrink: 0 }} />
                <span style={{ fontSize: 13.5, color: C.text, fontWeight: 600 }}>{c.name}</span>
                <span style={{ fontSize: 12.5, color: C.textSoft }}>· {closenessStage(c).label} · known {knownDuration(c)}</span>
              </div>
            ))}
          </>
        )}

        {lore.length > 0 && (
          <>
            <div style={label}>✨ Moments you've shared</div>
            {lore.slice(0, 8).map((l, i) => (
              <div key={i} style={{ marginBottom: 10 }}>
                <div style={{ fontSize: 10, color: C.textDim }}>{fmt(l.ts)}</div>
                <div style={{ fontSize: 13.5, color: C.text, lineHeight: 1.5 }}>remember when {l.text}</div>
              </div>
            ))}
          </>
        )}

        {jokes.length > 0 && (
          <>
            <div style={label}>😄 Inside jokes</div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
              {jokes.map((j, i) => <span key={i} style={{ padding: '6px 11px', borderRadius: 999, background: C.surface, border: `1px solid ${C.border}`, fontSize: 12.5, color: C.textSoft }}>{j.text}</span>)}
            </div>
          </>
        )}

        {letters.length > 0 && (
          <>
            <div style={label}>✉️ Letters</div>
            {letters.slice(0, 4).map((l, i) => (
              <div key={i} style={{ borderLeft: `2px solid ${l.color}`, paddingLeft: 12, marginBottom: 14 }}>
                <div style={{ fontSize: 10, color: C.textDim, marginBottom: 3 }}>{l.from} · {fmt(l.ts)}</div>
                <div style={{ fontSize: 13, color: C.text, lineHeight: 1.6, whiteSpace: 'pre-wrap' }}>{l.text}</div>
              </div>
            ))}
          </>
        )}

        {living.length > 0 && (
          <p style={{ fontFamily: "'Cormorant Garamond',serif", fontSize: 17, fontStyle: 'italic', color: C.textSoft, textAlign: 'center', margin: '28px 0 0', lineHeight: 1.5 }}>Here's to more, {name}. ✦</p>
        )}
      </div>
    </Shell>
  );
}
